%.class: %.java
	javac $<

CLASSES = \
page/Page.java \
page/PageManager.java \
main/GUIInterface.java \
error/ErrorManager.java \
database/DatabaseManager.java \
main/CommandInterface.java \
main/Dashboard.java

classes: $(CLASSES:.java=.class)